### ISSUE TITLE
Support more Databases

### ISSUE THREAD

**Issue by abhijithneilabraham** [abhijithneilabraham/tableQA#24]
Currently the project supports queries of sqlite format only(See database.py) . However, integrating other databases like MySQL and postgreSQL could be done by mirroring the work similar to sqlite.

**Comment by nsankar** [comment]
@abhijithneilabraham  please also include Amazon S3 bucket-name as a source for CSV files  with an option for users to input their AWS credentials / config (IAM access key and secret key) through the front-end .

For AWS S3 integration , AWS DataWrangler is a great library to explore...
 https://github.com/awslabs/aws-data-wrangler 

It also supports direct access to AWS MySQL and PostGres that tou may integrate 
(The users from the front end, could select S3, mySQL or Postgress config )

**Comment by abhijithneilabraham** [comment]
@nsankar  Sounds cool. Was already thinking about something similar, thanks!
