### ISSUE TITLE
Support for data visualisations

### ISSUE THREAD

**Issue by abhijithneilabraham** [abhijithneilabraham/tableQA#25]
The output from the database could be used for generating pie charts, bar graphs, etc using pandas or any visualisation libraries. Add features to enable the same.

**Comment by abhijithneilabraham** [comment]
Sure. That would be great. Let me know if you need some heads up and pointers on how to do this.

**Comment by Damanpreet** [comment]
@abhijithneilabraham yes, that would be great.

**Comment by abhijithneilabraham** [comment]
@Damanpreet yes. https://join.slack.com/t/newworkspace-ehh1873/shared_invite/zt-hp3i6ic7-exMal1I4ZmFMWaHAwXk8HA
