### ISSUE TITLE
Using own data

### ISSUE THREAD

**Issue by sophgit** [abhijithneilabraham/tableQA#41]
Hello,
Thank you for providing your code! I'm very new to this and tried using my own data by simply feeding a CSV file into the pandas dataframe in the sample.ipynb. 
This doesn't seem to work. When I try to ask a question with agent.query_db it throws me an OperationalError.
What are the necessary steps to try the code on own CSV files?
Thank you in advance.

**Comment by abhijithneilabraham** [comment]
You just need to load the csv as a dataframe, like
import pandas
df=pd.read_csv("something.csv")
agent=Agent(df)
response=agent.query_db("your question)
print(response)

**Comment by sophgit** [comment]
I tried that before and it didn't work. Now it does, so I probably got something wrong earlier. Thank you!
