### ISSUE TITLE
Support for distinct

### ISSUE THREAD

**Issue by abhijithneilabraham** [abhijithneilabraham/tableQA#47]
Need a distinct=true parameter for `get_query` and `query_db` inside `agent.py`. This means the SQL query will be `SELECT DISTINCT(Something) FROM table` . Refer the `Clause.adapt` in clause.py to see how this can be done.

**Comment by abhijithneilabraham** [comment]
> Need a distinct=true parameter for `get_query` and `query_db` inside `agent.py`. This means the SQL query will be `SELECT DISTINCT(Something) FROM table` . Refer the `Clause.adapt` in clause.py to see how this can be done.

@abhijitramesh  You can take this up.

**Comment by abhijitramesh** [comment]
@abhijithneilabraham on it
