### ISSUE TITLE
Use of Schema Format

### ISSUE THREAD

**Issue by malcolm1232** [abhijithneilabraham/tableQA#52]
Schema Format:
{
    "name": DATABASE NAME,
    "keywords":[DATABASE KEYWORDS],
    "columns":
    [
        {
        "name": COLUMN 1 NAME,
        "mapping":{
            CATEGORY 1: [CATEGORY 1 KEYWORDS],
            CATEGORY 2: [CATEGORY 2 KEYWORDS]
        }

        },
        {
        "name": COLUMN 2 NAME,
        "keywords": [COLUMN 2 KEYWORDS]
        },
        {
        "name": "COLUMN 3 NAME",
        "keywords": [COLUMN 3 KEYWORDS],
        "summable":"True"
        }
    ]
}

Hi, I ould like to check how to utilize the Schema Format.
Could you kindly provide an example on how to use them?
Thanks a ton in advance!!
It would be most gracefully appreciated!

**Comment by abhijithneilabraham** [comment]
Hi, you could check out the colab notebook provided in the readme, an example schema is used there.

**Comment by abhijithneilabraham** [comment]
Closing the issue
