### ISSUE TITLE
requirements, versions - compatibility issues

### ISSUE THREAD

**Issue by TutajITeraz** [abhijithneilabraham/tableQA#71]
Hi!
Can you, please, upload requirements.txt with python packages versions that are working with your code?
For example i had to manually download Cython, but  it warns me about deprecated code and throws errors:

```
warning: /tmp/easy_install-9_mu3wk6/numpy-1.18.0/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310

Error compiling Cython file:
------------------------------------------------------------
...
    def __init__(self, seed=None):
        BitGenerator.__init__(self, seed)
        self.rng_state.pcg_state = &self.pcg64_random_state

        self._bitgen.state = <void *>&self.rng_state
        self._bitgen.next_uint64 = &pcg64_uint64
                                   ^
------------------------------------------------------------

_pcg64.pyx:113:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'. Exception values are incompatible. Suggest adding 'noexcept' to type 'uint64_t (void *) except? -1 nogil'.
```

I'm afraid that, with repository this old, i can expect many more compatibility issues. 

Using pip:
`pip install tableqa`
also is not working.

**Comment by DionizasA** [comment]
Hi, have the same issue. Tried to download the Cyphon, but it still throws an error.

**Comment by siddheshgunjal** [comment]
Hello @TutajITeraz I was able to resolve the dependency issue. I had to manually install some packages and then install tableqa via pip. I'll be raising a pull request to fix this dependency issue. Till then here's the `requirement.txt` I used to make this project work.

**Comment by TutajITeraz** [comment]
Dear @siddheshgunjal, 
Thank you for your help! Unfortunately, the above error (Error compiling Cython file) still occurs when I try to install dependencies with the command:
` pip install -r requrements.txt ` 

I'll let you know if I manage to fix it.
I also tried with uninstalling cython first using ` pip uninstall cython `
but it does not change anything.

**Comment by siddheshgunjal** [comment]
I'm using `Python 3.7.16` as sometimes `tensorflow==2.3.1` just fails to run on above python versions.

**Comment by siddheshgunjal** [comment]
Dear @TutajITeraz ,
 
I have modified the requirement file and created a test build on test-pypi of tableqa for testing purpose only.

Here's the updated `requirement.txt`
```
Cython==3.0.3
responder
graphql-core==2.3.2
graphene==2.1.8
numpy==1.18.5
matplotlib==3.3.4
pandas==1.1.5
cryptography==41.0.4
protobuf==3.20.2
click==7.1.2
tokenizers==0.8.1.rc2
tensorflow-cpu==2.3.1
tensorflow_hub
rake_nltk
nltk
sqlalchemy_utils
sqlalchemy==1.3.24
awswrangler==1.7.0
transformers[tf-cpu]==3.1.0
```

Install this first using `pip install -r requrements.txt` and then install the tableqa from test-pypi (created by me for testing only) which has updated build using following command: 
`pip install -i https://test.pypi.org/simple/ tableqa`

This method has been testing with `python 3.8.18` as for `python 3.7` and below, transformer package throws error.

Please try this method and update your finding with error code you receive if any. If this works, I'll raise a PR with fix.

**Comment by TutajITeraz** [comment]
Dear @siddheshgunjal,
I was using `Python 3.9.16` and switching to `3.8.18`  and using your `requirements.txt` resolved this issue for me.
Thank you!

**Comment by abhijithneilabraham** [comment]
Hi, Glad to see this was resolved. I shall upload a new release to pypi for tableQA it seems. Before that, can anyone push the appropriate requirements.txt or any other changes and make a PR? @siddheshgunjal @TutajITeraz

**Comment by siddheshgunjal** [comment]
@abhijithneilabraham I will raise a PR today itself
